### ISSUE TITLE
Understanding Logging

### ISSUE THREAD

**Issue by ruochen-z** [roosephu/slbo#5]
How do I make sense of the log.json? How can I retrieve the avg reward in term of samples (steps) like Figure 1 in the paper?

**Comment by roosephu** [comment]
You can find the lines in log.json whose `caller` is `main.py:30`, and the second element (index 1) of `args` is "Real Env". The fourth element (index 3) of `args` is the average reward at timestep i * FLAGS.rollout.n_train_samples.

**Comment by ruochen-z** [comment]
Thank you so much for the quick reply! For the avg reward of "Real Env", the 0th arg is "iteration" or "episode". Does the episode refers to the outer loop and iteration the inner loop? Do you use both to plot Figure 1. Also would you mind telling me how to find the timestep? Thanks again!
